### first request
GET http://localhost:3000/server

### Post a user to the database
POST http://localhost:3000/server/users
Content-Type: application/json

{
     "username" : "nico5",
     "password" : "1234"
    }
